### PR TITLE
gitignore generated files

### PR DESCRIPTION
**Pull request by szabgab**

### CODE REVIEW

**Comment by szabgab** [comment]
No, I did not. Interesting. Why don't you want to ignore generated files that don't belong to git?

**Comment by ap** [comment]
Because they exist only when I `make dist` (i.e. when I’m cutting a release) – and I `git clean` them out right after. The rest of the time the files do not exist, since tests can be run just fine with just `prove -l`¹ rather than full-on `make test` (and I make a point of ensuring that).

That way I never have outdated generated files sticking around, waiting to cause mysterious issues down the line (or embarrassing ones). And so in fact I *want* the generated files to be visible and a nuisance, so that I won’t forget to clean them out.

IMO generated files only make sense to keep around if they are perceptibly expensive to recreate, like `.o` files back in the ’90s (or today if you are compiling something gigantic like Chrome).

----

1. Well, `prove -I.` in the case of Memoize, since unfortunately it never had a `lib` directory.

**Comment by szabgab** [comment]
I am personally more worried of accidentally adding files to git (by using `git add .` and not checking what is being added).
Anyway, I am closing this PR and I hope I won't forget this and won't create a new one a few months from now :)

**Comment by ap** [comment]
> I am personally more worried of accidentally adding files to git (by using `git add .` and not checking what is being added).

Ah. That has never happened to me, I constantly review what I have staged, and I am instinctively vigilant about what got added when I `git add`. My problem is instead that I occasionally forget to `git add` new files – despite the double-checking. (It takes basically zero attention to spot a bogus extra file while looking at any diff, and a lot more situational awareness to notice a file is missing entirely in a nontrivial diff.)

> Anyway, I am closing this PR and I hope I won't forget this and won't create a new one a few months from now :)

:D

**Comment by szabgab** [comment]
My other PR #3 will help catching anything that you, or someone else might forget to commit.

**Pull request closed without merging**
